In [3]:
#range values using arange
import numpy as np
w = np.arange(1,24,2).reshape(3,4) #if reshape not defined values in sequential order i.e 1D
print(w)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [4]:
#print particular row
print("Row 0 is :",w[0])
print("Row 1 is :",w[1])
print("Row 2 is :",w[2])
print("Row -3 is :",w[-3])  #negative indexing

Row 0 is : [1 3 5 7]
Row 1 is : [ 9 11 13 15]
Row 2 is : [17 19 21 23]
Row -3 is : [1 3 5 7]


In [5]:
#SPrinting pecific Row (Slicing)
print("Row 1 and 2 is : ",w[0:2])
print("Row 2 and 3 is : ",w[1:])

Row 1 and 2 is :  [[ 1  3  5  7]
 [ 9 11 13 15]]
Row 2 and 3 is :  [[ 9 11 13 15]
 [17 19 21 23]]


In [6]:
#Reverse an array
print(w[::-1])

[[17 19 21 23]
 [ 9 11 13 15]
 [ 1  3  5  7]]


In [7]:
#columns access
print("column 0 is : ",w[:,0])
print("column 1 is : ",w[:,1])
print("column 2 is : ",w[:,2])
print("column 2 is : ",w[:,-1])    #negative indexing

column 0 is :  [ 1  9 17]
column 1 is :  [ 3 11 19]
column 2 is :  [ 5 13 21]
column 2 is :  [ 7 15 23]
