In [2]:
import numpy as np
y = np.ones((2,3))  #float values
print(y)

#integer values
y = np.ones((2,3),dtype = np.int32)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


In [3]:
z = np.zeros((3,2),dtype=np.int32)
print(z)

[[0 0]
 [0 0]
 [0 0]]


In [4]:
z = np.ones((3,2),dtype = [('m','int'),('n','float')])
print(z)

[[(1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.)]]


In [5]:
#range values using arange
w = np.arange(1,24,2).reshape(3,4) #if reshape not defined values in sequential order i.e 1D
print(w)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
